export default {
    IMAGE: {
        CAMERA: {
            OPEN: 'image.camera.open'
        },
        CODE:{
            SCANQRCODE:'image.code.scanQRCode'
        },
        ALBUM:{
            OPEN:'image.album.open'
        }
    },
    UI:{
        NAVIGATION:{
            PUSH:'ui.navigation.push',
            POP:'ui.navigation.pop',
            CLOSE:'ui.navigation.close',
            PRESENT:'ui.navigation.present'
        },
        STYLE:{
            SET_NAVIGATION_BAR_HIDDEN:'ui.style.setNavigationBarHidden',
            SET_NAVIGATION_BACKGROUND_COLOR:'ui.style.setNavigationBackgroundColor',
            SET_NAVIGATION_TITLE:'ui.style.setNavigationTitle',
            SET_STATUS_BAR_HIDDEN:'ui.style.setStatusBarHidden',
            SET_NAVIGATION_ITEM_COLOR:'ui.style.setNavigationItemColor',
            SET_STATUS_BAR_STYLE:'ui.style.setStatusBarStyle',
            GET_NAVIGATION_BAR_HEIGHT:'ui.style.getNavigationBarHeight'
        },
        SCREEN:{
            GET_WIDTH:'ui.screen.getWidth',
            GET_HEIGHT:'ui.screen.getHeight',
            ROTATE:'ui.screen.rotate'
        }
    },
    NET:{
        HTTP:{
            SYNC_REQUEST:'net.http.syncRequest',
            ASYNC_REQUEST:'net.http.asyncRequest',
            UPLOAD_FILE:'net.http.uploadFile',
            DOWNLOAD_FILE:'net.http.downloadFile'
        }
    },
    IO:{
        FILE:{
            DELETE_LONG_TERM_FILE:'io.file.deleteLongTermFile',
            DELETE_SHORT_TERM_FILE:'io.file.deleteShortTermFile',
            CLEAR_ALL_LONG_TERM_FILES:'io.file.clearAllLongTermFiles',
            CLEAR_ALL_SHORT_TERM_FILES:'io.file.clearAllShortTermFiles'
        }
    },
    MAP:{
        LOCATION:{
            GET_POSITION:'map.location.getPosition',
            ON_INSTANT_POSITION:'map.location.onInstantPosition',
            OFF_INSTANT_POSITION:'map.location.offInstantPosition',
        }
    },
    CALL:{
        CUSTOMS:{
            CALL_CUSTOM:'call.customs.callCustom'
        }
    },
    DATA:{
        STORAGE:{
            GET:'data.storage.get',
            SET:'data.storage.set',
            REMOVE:'data.storage.remove',
            CLEAR:'data.storage.clear'
        }
    },
    BIOMETRICS:{
        CHECK:{
            START:'biometrics.check.start'
        }
    }
}